[package]
name = "Reaction-resonance"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.5"
rand = "0.8.5"
rayon = "1.5.1"

[profile.release]
debug = true
lto = true
codegen-units = 1
panic = "abort"